SFC часть
js-tasks-ru/vue-20210119_itsu pull request #6
Opened 2021-02-05 20:34 UTC by itsuryev

Из примечательного в DropdownButton был вынужден сделать вот так:
```
      this.$emit('change', value);
      this.$emit('input', value);
```

По заданию надо `change` кидать, а чтобы моделька родительского компонента -- `input`

2021-02-05 20:40 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
DropdownButton-1
+ Компонент должен иметь параметры title, options, value
+ Кнопка должна иметь текст с заголовком из параметра
+ Кнопка должна иметь текст с заголовком и выбранным вариантом
+ Компонент должен реагировать на изменение выбранного варианта
+ Компонент должен показывать список скрытым, открывать его по клику и закрывать по повторному клику
+ Выбор вариант порождает событие change
+ Список должен скрываться после выбора варианта
+ Должен быть класс dropdown__toggle_icon и иконка на кнопке выбранного варианта при наличии icon в списке вариантов
+ Должен быть класс dropdown__item_icon на все вариантах, если хотя бы у одного есть иконка
```
```diff
AppToast
+ AppToast изначально не показывает ни одного тоста
+ AppToast должен выводить success тост с сообщением после вызова метода success
+ AppToast должен выводить error тост с сообщением после вызова метода error
+ AppToast должен выводить список тостов в порядке добавления
+ AppToast удалять тост через 5 секунд
```
```diff
CounterButton.vue
+ CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
+ CounterButton должен рендерить кнопку с текстом count
+ CounterButton должен выводить новое значение счётчика при его обновлении
+ CounterButton должен порождать событие increment с увеличенным на 1 значением после клика
```
```diff
FormGroup
+ FormGroup должен иметь параметры inline, label
+ FormGroup должен выводить содержимое в блоке .form-group
+ FormGroup не должен выводить label по умолчанию
+ FormGroup должен выводить label со значением параметра
+ FormGroup должен выводить слот после label
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2021-02-07 10:49 UTC, ShGKme requested changes
Требуется добавить описание модели в `DropdownButton` вместо дублирования события с `input`.

2021-02-07 10:49 UTC, ShGKme commented on 03-vue-cli/01-CounterButton-vue/components/CounterButton.vue
> +  },
Описывать `data` не требуется, если у компонента нет данных

2021-02-07 10:49 UTC, ShGKme commented on 03-vue-cli/02-FormGroup/components/FormGroup.vue
> +  <div :class="{ 'form-group': true, 'form-group_inline': inline }">
Классы, которые всегда есть у элемента, можно описывать явно в шаблоне через обычный атрибут `class="form-group"`. Так будет видно и основные классы вёрстки, и какие классы определяются динамически.

2021-02-07 10:49 UTC, ShGKme commented on 03-vue-cli/03-AppToast/components/AppToast.vue
> +    },
В основных правилах в стайл-гайде Vue не рекомендуется именовать свойства компонента с `_`. У Vue есть свои приватные свойства, которые начинаются с `_`, есть риск коллизий.
Хотя в официальных примерах есть примеры с методами с такими именами.
https://vuejs.org/v2/style-guide/#Private-property-names-essential

2021-02-07 10:49 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +        hasIcon ? 'dropdown__toggle_icon' : '',
В таких случаях лучше использовать описание классов через объект: `{ 'dropdown__toggle_icon': hasIcon }`

2021-02-07 10:49 UTC, ShGKme commented on 03-vue-cli/04-DropdownButton-1/components/DropdownButton.vue
> +      this.$emit('input', value);
Хотя модель по умолчанию работает на свойстве `value` с событием `input`, она может настраиваться явно свойством `model` на любой входной параметр и любое событие.

[https://vuejs.org/v2/api/#model](https://vuejs.org/v2/api/#model)

2021-02-07 17:07 UTC, itsuryev commented on 03-vue-cli/02-FormGroup/components/FormGroup.vue
> +  <div :class="{ 'form-group': true, 'form-group_inline': inline }">
Огонь, не знал, что можно одновременно задать как `class`, так и `:class`

2021-02-07 17:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2021-02-08 21:03 UTC, ShGKme commented on 03-vue-cli/03-AppToast/components/AppToast.vue
> +      this.$_AppToast_renderToast({
Такой формат именования в документа предлагался для миксинов (о которых мы ещё не говорили), а не простых компонентов.
Какого-то общепринятого подхода к разделению методов на приватные и публичные во Vue (к **огромнейшему** сожалению) нет.

2021-02-08 21:04 UTC, ShGKme approved these changes
Все задачи приняты 👍

2021-02-08 21:05 UTC, merged