Remaining Router related tasks
js-tasks-ru/vue-20210119_itsu pull request #8
Opened 2021-02-22 19:46 UTC by itsuryev

2021-02-22 19:46 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-02-23 20:56 UTC, ShGKme requested changes
В `Layouts` немного не совпадает вёрстка. В остальном по решению во всех задачах всё ок.

2021-02-23 20:56 UTC, ShGKme commented on 04-SPA/04-Layouts/components/AuthLayout.vue
> +  </div>
Вёрстка не совпадает...
Вёрстка: https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/login.html#L30-L32
Стили: https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/styles/_page_onboarding.css

2021-02-23 20:56 UTC, ShGKme commented on 04-SPA/04-Layouts/components/FormLayout.vue
> +  </div>
Вёрстка: https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/meetup-form.html#L29-L31
Стили: https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/styles/_page_forms.css

2021-02-23 20:56 UTC, ShGKme commented on 04-SPA/04-Layouts/components/BaseLayout.vue
> +    <slot></slot>
Не хватает блока `main`:
https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/index.html#L30
И классов `wrapper bg-grey`: https://github.com/js-tasks-ru/vue-course-materials/blob/master/meetups-markup/meetup-form.html#L13

2021-02-24 09:26 UTC, itsuryev commented on 04-SPA/04-Layouts/components/BaseLayout.vue
> +    <slot></slot>
Тут не очень понял, что куда, но стало еще более похоже на скриншоты! :)

2021-02-24 09:29 UTC, ShGKme approved these changes
Принято 👍

2021-02-24 09:30 UTC, merged